services:
  admin_db: 
    container_name: admin_db
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=admin_db
      - TELEGRAM_TOKEN=7859460262:AAHTOvINtQPNG0xMhUIfWkeY4BruHBWILrY
      - TELEGRAM_CHAT_ID=711095751
    image: postgres:14
    volumes:
      - './data/db:/var/lib/postgresql/data'
